baseURL = "https://adhikasp.my.id/"
languageCode = "en-us"
title = "Adhika Setya Pramudita"
theme = "ink-free"
enableRobotsTXT = true
tableOfContents = true

[_build]
list = 'always'
publishResources = true
render = 'always'

[params]
subtitle = "Collection of thoughts"
mainSections = ["posts", "link-blog", "notebook"]
wpm = 150
featherIconsCDN = true
maxTags = 5
mermaidCDN = "https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.esm.min.mjs"
customcss = "mine.css"

[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    style = "github"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "My other projects"
url = "/public-service"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[params.social]]
name = "Stack Overflow"
url = "https://stackoverflow.com/users/4504053/adhika-setya-pramudita"
icon = "layers"

[[params.social]]
name = "LinkedIn"
url = "https://linkedin.com/in/adhikasp"
icon = "linkedin"

[[params.social]]
name = "Github"
url = "https://github.com/adhikasp"
icon = "github"

[[params.social]]
name = "Gitlab"
url = "https://gitlab.com/adhikasp"
icon = "gitlab"

[[params.social]]
name = "Instagram"
url = "https://www.instagram.com/adhikasp/"
icon = "instagram"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"