baseURL = "https://adhikasp.my.id/"
languageCode = "en-us"
title = "Adhika Setya Pramudita"
theme = "ink-free"
enableRobotsTXT = true

[_build]
list = 'always'
publishResources = true
render = 'always'

[params]
subtitle = "Collection of thoughts"
mainSections = ["posts"]
wpm = 150
featherIconsCDN = true
maxTags = 5

[markup.goldmark.renderer]
unsafe = true

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "My other site"
url = "/public-service"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[params.social]]
name = "Stack Overflow"
url = "https://stackoverflow.com/users/4504053/adhika-setya-pramudita"
icon = "layers"

[[params.social]]
name = "LinkedIn"
url = "https://linkedin.com/in/adhikasp"
icon = "linkedin"

[[params.social]]
name = "Github"
url = "https://github.com/adhikasp"
icon = "github"

[[params.social]]
name = "Gitlab"
url = "https://gitlab.com/adhikasp"
icon = "gitlab"

[[params.social]]
name = "Instagram"
url = "https://www.instagram.com/adhikasp/"
icon = "instagram"
